### ISSUE TITLE
The sourcepath isn't escaped when the deploy is called

### ISSUE THREAD

**Issue by anormanbmj** [omniphx/sfdx-autodeploy-watcher#1]
The extension doesn't escape the path that it passes to **sfdx**. If your path contains spaces the call to **sfdx** fails.

What it sends to **sfdx**:

`sfdx force:source:deploy --sourcepath /Users/andy/Dropbox/clients/cpqstaging/CPQ Staging/force-app/main/default/classes/TestUtils.cls`

What it should send to **sfdx**:

`sfdx force:source:deploy --sourcepath '/Users/andy/Dropbox/clients/cpqstaging/CPQ Staging/force-app/main/default/classes/TestUtils.cls'`

**Comment by anormanbmj** [comment]
Although, reading up on escaping and node's exec, it seems like a problem lots if people are struggling with, naive escaping probably isn't the right answer after all.

https://github.com/shelljs/shelljs/issues/143

**Comment by omniphx** [comment]
Thanks for reporting @anormanbmj! I just published a new version (0.0.6) with this fix in place. Seemed to be working fine when I tested out but let me know if it continues to be an issue.

**Comment by anormanbmj** [comment]
That _does_ fix my particular issue, thank you for getting an update out so quickly.

However it isn't a general fix, that code path will still break in some cases. For example if there is a single quote in the path, which is perfectly possible and valid on MacOS for example, then it will still break. There will also be other non alpha numeric characters that are going to break it.

I also doubt that the single quote escaping is going to work cross platform in all cases. It has been a while since I did any Windows command line stuff, but I'm fairly sure you can't escape command line arguments with single quotes there.

Sadly it doesn't look like there is a quick and easy solution to fix it fully.

**Comment by omniphx** [comment]
Oh I see your point. I think the file path I'm using from VS Code's API documentation: `TextDocument.fileName` (https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocument) is suppose to normalize the path string. I'll test it out with some of my co-workers using Windows machines.

For special characters.. might just let that slide for now. I'm planning on deprecating the package once this feature is included in the Salesforce extension. I think it will be Spring GA.
